ersion: '3.8'

services:
  servercielo:
    build: .
    ports:
      - "5002:5002"
    dependes_on:
      - db 

db:
  image: postgres:15
  enviroment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: cielo
  ports:
    - "5432:5432"
  volumes:
     - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
